# This action builds the PhonWork website and copies the files to the
# site-dev or site-prod branch.

name: Build phonwork website and deploy to a site-* branch

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: Branch to which generated site will be pushed
        type: choice
        required: true
        options:
        - site-dev
        - site-prod
      submodules:
        description: Checkout submodules?
        type: choice
        required: true
        options:
        - false
        - true
        default: true

env:
  REPO: "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

jobs:
  build:
    runs-on: ubuntu-20.04
 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: ${{ inputs.submodules }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2

      - name:  build_site
        run: |
          cd scripts && \
          echo "::debug::generating site"
          python generate.py
          if [ ${{ inputs.submodules }} = 'true' ]
          then
            echo "::debug::Moving submodule directories to site/"
            git submodule foreach 'cd .. && export dest=`echo "${sm_path}" | sed 's/^_//'` && mv "${sm_path}" site/${dest}'
          else
            echo "::debug::Not including submodules in site/"
          fi
          echo "::debug::Initializing new repo (branch named 'mysite')"
          cd ../site && \
          git init -b mysite && \
          git config user.name "${GITHUB_ACTOR}" && \
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
          git add . && \
          git commit -m "Site build from workflow action" && \
          echo "::debug::Pushing to target branch" && \
          echo "::debug::${REPO}" && \
          echo "::debug::${{ inputs.target_branch }}" && \
          echo "::debug::git push --force ${REPO} mysite:${{ inputs.target_branch }}" && \
          echo "::debug::pushing" && \
          git push --force $REPO mysite:${{ inputs.target_branch }} && \
          echo "SHA=$( git rev-parse mysite )" >> $GITHUB_OUTPUT
          rm -rf .git && \
          cd ..

