# This action builds the PhonWork website and copies the files to the
# site-dev or site-prod branch.

name: Build phonwork website and deploy to a site-* branch

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: Branch to which generated site will be pushed
        type: choice
        required: true
        options:
        - site-dev
        - site-prod

env:
  REPO: "https://${GITHUB_ACTOR}:${secrets.GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

jobs:
  build:
    runs-on: ubuntu-20.04
 
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2

      - name:  build_site
        run: |
          cd scripts && \
          echo "::debug::generating site"
          python generate.py && \
          echo "::debug::generated site"
          echo "::debug::GITHUB_ACTOR is ${GITHUB_ACTOR}."
          git config user.name "${GITHUB_ACTOR}" && \
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
          echo "::debug::commit author is set to the default github actor"
          echo "::debug::Initializing new repo (branch named 'mysite')"
          cd ../site && \
          git init -b mysite && \
          git add . && \
          git commit -m "Site build from workflow action" && \
          echo "::debug::Pushing to target branch" && \
          git push --force $REPO mysite:${inputs.target_branch} && \
          echo "SHA=$( git rev-parse mysite )" >> $GITHUB_OUTPUT
          rm -rf .git && \
          cd .. 

